# Generated by Django 3.2.4 on 2021-08-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postm',
            name='document',
            field=models.FileField(null=True, upload_to='postM//', verbose_name='음악파일'),
        ),
    ]
