# Generated by Django 3.2.4 on 2021-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_comments_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenti',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commentI/'),
        ),
        migrations.AddField(
            model_name='commentm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='commentM/'),
        ),
    ]
