# Generated by Django 3.2.5 on 2021-08-13 02:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20210813_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='likes_user_setS', through='mainapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
