# Generated by Django 3.2.5 on 2021-07-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_blog_comments_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='postD/')),
            ],
        ),
        migrations.DeleteModel(
            name='CommentS',
        ),
    ]
