# Generated by Django 3.1.7 on 2021-07-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_postd'),
        ('mainapp', '0005_auto_20210704_0439'),
    ]

    operations = [
    ]
