# Generated by Django 3.1.7 on 2021-07-04 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_merge_20210704_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postd',
            name='image',
            field=models.ImageField(null=True, upload_to='postD/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='writer',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CommentS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.posts')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
