# Generated by Django 3.2.5 on 2021-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
