# Generated by Django 3.2.5 on 2021-08-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
